### ISSUE TITLE
Todo: Voice Server Configuration

### ISSUE THREAD

**Issue by Cryma** [AlternateLife/JustAnotherVoiceChat-Server#31]
- [X] Position task update frequency
- [X] Global settings like RollOffScale, MaxDistance etc
- [X] "Read-only" settings like hostname, port and channel id
